cookie:
  expiry_days: 2
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    edy:
      email: edy.stein@gmail.com
      name: Edy Stein
      password: $2b$12$NFmFcLjD4thYzOXto9Pp/.yBxLmW4de1YkzvPjANksitK5EoRqUXa
#      123
    itamar:
      email: edy.stein@gmail.com
      name: Itamar the King Stein
      password: $2b$12$NFmFcLjD4thYzOXto9Pp/.yBxLmW4de1YkzvPjANksitK5EoRqUXa
#      123
preauthorized:
  emails:
  - edy.stein@gmail.com
